version: '3'
volumes:
  dados:
networks:
  otus-api:
    driver: bridge
  otus-front:
    driver: bridge
  otus-db:
    driver: bridge
services:
  mongodb_server:
    image: mongo:3.6
    container_name: mongodb_server
    env_file:
      - .env
    volumes:
      - ${DATA-./mongodb/mongoData/}:/data/db/
      - ./mongodb/mongod.conf:/etc/mongo.conf
      - ${DB_BUILD_SCRIPT-./mongodb/dumie.js}:/docker-entrypoint-initdb.d/initdb.js
    networks:
      - otus-db
    ports:
      - 27017:27017
    command:
      - '--auth'
      - '-f'
      - '/etc/mongo.conf'
  nginx_server:
    container_name: nginx_server
    image: nginx:1.12.1
    depends_on:
      - wildfly_server
    volumes:
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled/
      - ./nginx/sites-available:/etc/nginx/sites-available/
      - ${NGINX_CONF_PATH-./nginx/nginx.conf}:/etc/nginx/nginx.conf
    networks:
      - otus-front
      - otus-api
    ports:
      - 80:80
      - 443:443
    entrypoint: nginx
    command:
      - '-g'
      - 'daemon off;'
  wildfly_server:
    container_name: wildfly_server
    image: jboss/wildfly:9.0.1.Final
    volumes:
      - ./wildfly/standalone.xml:/opt/jboss/wildfly/standalone/configuration/standalone.xml
      - ./wildfly/standalone.conf:/opt/jboss/wildfly/bin/standalone.conf
    depends_on:
      - mongodb_server
    networks:
      - otus-api
      - otus-db
    ports:
      - 9990:9990
      - 8080:8080
